src/Entity/Islas.php
<?php

namespace App\Entity;

use App\Repository\IslasRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=IslasRepository::class)
 */
class Islas
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nombre;

    /**
     * @ORM\ManyToMany(targetEntity=Ofertas::class, inversedBy="islas")
     */
    private $id_isla;

    public function __construct()
    {
        $this->id_isla = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->Nombre;
    }

    public function setNombre(string $Nombre): self
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    /**
     * @return Collection|Ofertas[]
     */
    public function getIdIsla(): Collection
    {
        return $this->id_isla;
    }

    public function addIdIsla(Ofertas $idIsla): self
    {
        if (!$this->id_isla->contains($idIsla)) {
            $this->id_isla[] = $idIsla;
        }

        return $this;
    }

    public function removeIdIsla(Ofertas $idIsla): self
    {
        $this->id_isla->removeElement($idIsla);

        return $this;
    }
}

src/Entity/Preguntas.php
<?php

namespace App\Entity;

use App\Repository\PreguntasRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PreguntasRepository::class)
 */
class Preguntas
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Pregunta;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Requerido;

    /**
     * @ORM\ManyToOne(targetEntity=Ofertas::class, inversedBy="preguntas_id")
     * @ORM\JoinColumn(nullable=false)
     */
    private $oferta;

    /**
     * @ORM\OneToMany(targetEntity=Respuestas::class, mappedBy="pregunta")
     */
    private $Respuesta;

    public function __construct()
    {
        $this->Respuesta = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPregunta(): ?string
    {
        return $this->Pregunta;
    }

    public function setPregunta(string $Pregunta): self
    {
        $this->Pregunta = $Pregunta;

        return $this;
    }

    public function getRequerido(): ?bool
    {
        return $this->Requerido;
    }

    public function setRequerido(bool $Requerido): self
    {
        $this->Requerido = $Requerido;

        return $this;
    }

    public function getOferta(): ?Ofertas
    {
        return $this->oferta;
    }

    public function setOferta(?Ofertas $oferta): self
    {
        $this->oferta = $oferta;

        return $this;
    }

    /**
     * @return Collection|Respuestas[]
     */
    public function getRespuesta(): Collection
    {
        return $this->Respuesta;
    }

    public function addRespuestum(Respuestas $respuestum): self
    {
        if (!$this->Respuesta->contains($respuestum)) {
            $this->Respuesta[] = $respuestum;
            $respuestum->setPregunta($this);
        }

        return $this;
    }

    public function removeRespuestum(Respuestas $respuestum): self
    {
        if ($this->Respuesta->removeElement($respuestum)) {
            // set the owning side to null (unless already changed)
            if ($respuestum->getPregunta() === $this) {
                $respuestum->setPregunta(null);
            }
        }

        return $this;
    }
}

src/Form/OfertasType.php
<?php

namespace App\Form;

use App\Entity\Ofertas;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OfertasType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('descripcion')
            ->add('puesto')
            ->add('fecha')
            ->add('tipo')
            ->add('id_empresa', EmpresasType::class)
            ->add('categoria')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Ofertas::class,
        ]);
    }
}

src/Controller/OfertasController.php
<?php

namespace App\Controller;

use App\Entity\Ofertas;
use App\Entity\Preguntas;
use App\Entity\Respuestas;
use App\Entity\UsuariosEmpresasOfertas;
use App\Form\OfertasType;
use App\Repository\CategoriasRepository;
use App\Repository\EmpresasRepository;
use App\Repository\IslasRepository;
use App\Repository\OfertasRepository;
use App\Repository\PreguntasRepository;
use App\Repository\RespuestasRepository;
use App\Repository\UsuariosEmpresasOfertasRepository;
use App\Repository\UsuariosRepository;
use App\Service\Correos;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Mime\Email;

/**
 * @Route("/ofertas")
 */
class OfertasController extends AbstractController
{
    /**
     * Funcion que genera la lista de las ofertas.
     * @Route("/lista", name="ofertas_index", methods={"GET", "POST"})
     */
    public function index(OfertasRepository $ofertasRepository, Request $request, CategoriasRepository $categoriasRepository, IslasRepository $islasRepository): Response
    {

        // Lista de ofertas con un parametro de busqueda
        if ($request->get('busqueda') != "") {
            return $this->render('ofertas/index.html.twig', [
                'ofertas' => $ofertasRepository->ofertasBusqueda($request->get('busqueda')),
                'categorias' => $categoriasRepository->findAll(),
                'islas' => $islasRepository->findAll()
            ]);
        }

        // Lista de ofertas eligiendo una categoria
        if ($request->query->get('categorias') != "") {
            return $this->render('ofertas/index.html.twig', [
                'ofertas' => $ofertasRepository->ofertasCategorias($request->query->get('categorias')),
                'categorias' => $categoriasRepository->findAll(),
                'islas' => $islasRepository->findAll()
            ]);
        }

        // Lista de ofertas eligiendo una fecha
        if ($request->query->get('fecha1') != "" && $request->query->get('fecha2') != "") {
            return $this->render('ofertas/index.html.twig', [
                'ofertas' => $ofertasRepository->ofertasFecha($request->query->get('fecha1'), $request->query->get('fecha2')),
                'categorias' => $categoriasRepository->findAll(),
                'islas' => $islasRepository->findAll()
            ]);
        }
        // Lista de oferta si esta activa o no
        if ($request->query->get('actividad') != "") {
            return $this->render('ofertas/index.html.twig', [
                'ofertas' => $ofertasRepository->ofertasActividad($request->query->get('actividad')),
                'categorias' => $categoriasRepository->findAll(),
                'islas' => $islasRepository->findAll()
            ]);
        }
        // Lista de ofertas si has elegido una isla
        if ($request->query->get('localizacion') != "") {

            return $this->render('ofertas/index.html.twig', [
                'ofertas' => $ofertasRepository->ofertasLoc($request->query->get('localizacion')),
                'categorias' => $categoriasRepository->findAll(),
                'islas' => $islasRepository->findAll()
            ]);
        }

        // Lista de ofertas por defecto
        return $this->render('ofertas/index.html.twig', [
            'ofertas' => $ofertasRepository->findAll(),
            'categorias' => $categoriasRepository->findAll(),
            'islas' => $islasRepository->findAll()
        ]);
    }

    /**
     * Lista de las ofertas a las que esta inscrito un usuario
     * @Route("/listaUsuario", name="ofertas_listausuario", methods={"GET"})
     */
    public function listaUsuario(OfertasRepository $ofertasRepository, SessionInterface $session, UsuariosRepository $usuariosRepository, UsuariosEmpresasOfertasRepository $triple): Response
    {
        $usuario = $usuariosRepository->findOneBy(['id' => $session->get('usuario')['id']]);

        return $this->render('ofertas/listaUsuario.html.twig', [
            'ofertas' => $triple->findBy(['usuarios' => $usuario]),
        ]);
    }

    /**
     * Genera la lista de las ofertas que ha creado una empresa
     * @Route("/listaEmpresas", name="ofertas_listaempresas", methods={"GET"})
     */
    public function listaEmpresas(OfertasRepository $ofertasRepository, SessionInterface $session, EmpresasRepository $empresasRepository): Response
    {
        $empresa = $empresasRepository->findOneBy(['id' => $session->get('empresa')['id']]);

        return $this->render('ofertas/listaEmpresa.html.twig', [
            'ofertas' => $ofertasRepository->findBy(['id_empresa' => $empresa]),
        ]);
    }


    /**
     * Funcion para crear una oferta
     * @Route("/crear", name="ofertas_crear", methods={"GET","POST"})
     */
    public function crearOferta(Request $request, EntityManagerInterface $em, SessionInterface $session, CategoriasRepository $categoriasRepository, EmpresasRepository $empresasRepository, IslasRepository $islasRepository): Response
    {
        $oferta = new Ofertas();
        $descripcion = $request->request->get('descripcion');
        $puesto = $request->request->get('puesto');
        $fecha = new \DateTime();
        $tipo = $request->request->get('tipo');
        $categoria = $request->request->get('categoria');
        $preguntas = $request->request->get('field_name');

        if (!empty($descripcion)) {

            $em = $this->getDoctrine()->getManager();
            //Añade al objeto Oferta los distintos campos necesarios
            $oferta->setDescripcion($descripcion);
            $oferta->setPuesto($puesto);
            $oferta->setFecha($fecha);
            $oferta->setTipo($tipo);
            $empresa = $empresasRepository->findOneBy(['id' => $session->get('empresa')['id']]); //Recoge el id de la sesion de la empresa
            $oferta->setIdEmpresa($empresa);
            $categorias = $categoriasRepository->findOneBy(['id' => $categoria]); //Busca el id de la categoria
            $oferta->setCategoria($categorias);
            $oferta->setActivo(true);
            // Se marca si la oferta se ha guardado en borrador o no
            if ($request->get('guardar')) {
                $oferta->setBorrador(true);
            } else {
                $oferta->setBorrador(false);
            }
            //Añade las islas indicadas a la oferta.
            for ($i = 0; $i < 9; $i++) {
                if ($request->get('isla' . $i) != "") {
                    $oferta->addIsla($islasRepository->findOneBy(['id' => $request->get('isla' . $i)]));
                }
            }

            $em->persist($oferta);
            $em->flush();
            // Creacion de las preguntas.
            foreach ($preguntas as $valor) {
            // Si la pregunta esta vacia, no se guarda
                if ($valor !=  "") {
                    $pregunta = new Preguntas();
                    $pregunta->setPregunta($valor);
                    $pregunta->setRequerido(true);
                    $pregunta->setOferta($oferta);
                    $em->persist($pregunta);
                    $em->flush();
                }
            }
            
            return $this->redirectToRoute('empresas_perfil');
        }
        return $this->render('ofertas/crear.html.twig', [
            'oferta' => $oferta,
            'categorias' => $categoriasRepository->findAll(),
            'islas' => $islasRepository->findAll()
        ]);
    }


    /**
     * Funcion para que un usuario se registre en una oferta
     * @Route("/registro", name="ofertas_registro", methods={"GET","POST"})
     */
    public function registroOferta(Request $request, EntityManagerInterface $em, SessionInterface $session, EmpresasRepository $empresasRepository, UsuariosRepository $usuariosRepository, OfertasRepository $ofertasRepository, MailerInterface $mailer, PreguntasRepository $preguntasRepository, Correos $correos): Response
    {

        $registro = new UsuariosEmpresasOfertas();

        $usuario = $usuariosRepository->findOneBy(['id' => $session->get('usuario')['id']]);
        $idempresa = $request->request->get('idempresa');
        $idoferta = $request->request->get('idoferta');
        $correo = $usuario->getCorreo();
        $empresa = $empresasRepository->findOneBy(['id' => $idempresa]);
        $oferta = $ofertasRepository->findOneBy(['id' => $idoferta]);
        $respuestas = $request->request->get('respuesta');
        $preguntas = $request->request->get('preguntaid');

        if (!empty($oferta)) {
            $em = $this->getDoctrine()->getManager();
            $registro->setIdEmpresa($empresa);
            $registro->setOfertas($oferta);
            $registro->setUsuarios($usuario);
            // Se añaden las respuestas a las preguntas realizadas
            if ($respuestas != "") {
                for ($i = 0; $i < count($respuestas); $i++) {
                    $respuesta = new Respuestas();
                    $respuesta->setRespuesta($respuestas[$i]);
                    $respuesta->setUsuario($usuario);
                    $respuesta->setPregunta($preguntasRepository->findOneBy(['id' => $preguntas[$i]]));
                    $em->persist($respuesta);
                    $em->flush();
                }
            }
            $em->persist($registro);
            $em->flush();

            // Manda un correo al usuario confirmando que se ha registrado en la oferta
            $mensaje = '<p>¡Te has registrado a una nueva oferta de Skeleton Jobs! </p>';
            $asunto = 'Se ha registrado en una oferta';
            $correos->crearCorreo($correo, $empresa, $oferta, $asunto, $mensaje);
        }

templates/ofertas/_delete_form.html.twig
<form method="post" action="{{ path('ofertas_delete', {'id': oferta.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ oferta.id) }}">
    <button class="btn">Delete</button>
</form>

templates/ofertas/_formulario.html.twig
<div>
    <form action="{{ accion }}" method="post" class="formulario" onsubmit="manejador(event)">
        <label for="puesto">Puesto: </label>
        <input type="string" name="puesto" id="puesto" required><br>
        <label for="descripcion">Descripcion: </label>
        <textarea name="descripcion" id="descripcion"></textarea><br>
        <label for="tipo">Tipo de conrato: </label>
        <input type="string" name="tipo" id="tipo" required><br>
        <select name="categoria" id="">
            {% for categoria in categorias %}
            <option value="{{categoria.id}}">{{categoria.nombre}}</option>
            {% endfor %}
        </select><br>
        <label for="">Seleccion localizacion</label>
        {% for isla in islas %}
        <label for="isla{{isla.id}}"></label>
        <input type="checkbox" value="{{isla.id}}" name="isla{{isla.id}}" id="isla{{isla.id}}">{{isla.nombre}}<br>
        {% endfor %}
        <br>

        <div class="field_wrapper">
            <div>
                <label for="Preguntas">Preguntas</label>
                <input type="text" name="field_name[]" value="" />
                <a href="javascript:void(0);" class="add_button" title="Add field">Añadir</a>
            </div>
        </div><br><br>

        <input style="width:50%;" class="button primary" type="submit" value="Crear Oferta" name="publicar"><br><br>
        <input style="width:50%;" class="button primary" type="submit" value="Guardar Borrador" name="guardar">
    </form>
</div>

{% if error is defined %}

<p>{{ error }}</p>

{% endif %}

templates/ofertas/editar.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Ofertas{% endblock %}

{% block javascripts %}

<script src="{{asset('js/validarIsla.js')}}"></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="{{asset('js/jquery.min.js')}}"></script>
<script src="{{asset('js/jquery.scrolly.min.js')}}"></script>
<script src="{{asset('js/jquery.dropotron.min.js')}}"></script>
<script src="{{asset('js/jquery.scrollex.min.js')}}"></script>
<script src="{{asset('js/browser.min.js')}}"></script>
<script src="{{asset('js/breakpoints.min.js')}}"></script>
<script src="{{asset('js/util.js')}}"></script>
<script src="{{asset('js/main.js')}}"></script>

<script type="text/javascript">
    $(document).ready(function () {
        var maxField = 10; //Input fields increment limitation
        var addButton = $('.add_button'); //Add button selector
        var wrapper = $('.field_wrapper'); //Input field wrapper
        var fieldHTML = '<div><input type="text" name="field_name[]" value=""/><a href="javascript:void(0);" class="remove_button" title="Remove field">Borrar</a></div>'; //New input field html 
        var x = 1; //Initial field counter is 1
        $(addButton).click(function () { //Once add button is clicked
            if (x < maxField) { //Check maximum number of input fields
                x++; //Increment field counter
                $(wrapper).append(fieldHTML); // Add field html
            }
        });
        $(wrapper).on('click', '.remove_button', function (e) { //Once remove button is clicked
            e.preventDefault();
            $(this).parent('div').remove(); //Remove field html
            x--; //Decrement field counter
        });
    });
</script>

{% endblock javascripts %}

{% block body %}
<div class="editar">
    <h1 style="font-size: 2em;">Editar oferta</h1>
    <div class="formulario">
        <form action="{{ path('ofertas_editar', {'id': oferta.id}) }}" method="post">
            <h2>Detalles básicos</h2>
            <label for="descripcion">Descripcion: </label>
            <textarea id="descripcion" name="descripcion"> {{ oferta.descripcion }}</textarea><br>

            <label for="puesto">Puesto: </label>
            <input type="text" name="puesto" id="puesto" value="{{ oferta.puesto }}"><br>

            <label for="tipo">Tipo de contrato: </label>
            <input type="text" name="tipo" id="tipo" value="{{ oferta.tipo }}" required><br>



            <h2>Categorias</h2>
            <select name="categoria" id="categoria">
                {% for categoria in categorias %}
                <option value="{{categoria.id}}">{{categoria.nombre}}</option>
                {% endfor %}
            </select><br>
            <br><br>

            <h2>Islas</h2>
            {% for isla in islas %}
            <input type="checkbox" value="{{isla.id}}" name="isla{{isla.id}}" id="isla{{isla.id}}">{{isla.nombre}}<br>
            {% endfor %}
            <br><br>
            <h2>Preguntas</h2>
            <div class="field_wrapper">
                <div>
                    {% for pregunta in preguntas %}
                    <label for="Preguntas">Preguntas</label>
                    <input type="text" name="field_name[]" value="{{pregunta.Pregunta}}" /><br>
                    {% endfor %}
                    <a href="javascript:void(0);" class="add_button" title="Add field">Añadir</a><br><br>
                </div>
            </div>

            <input class="button primary" style="width:60%" type="submit" value="Publicar" name="publicar"><br><br>
            <input class="button primary" style="width:60%" type="submit" value="Guardar Borrador" name="guardar">
        </form>
        <a class="button primary" style="width:60%;" href="{{ path('ofertas_cerrar', {'id': oferta.id}) }}">Cerrar oferta</a>
    </div>
    <a class="button primary"style="width:60%" href="{{ path('empresas_perfil') }}">Atras</a>
</div>
{% endblock %}

templates/ofertas/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Lista ofertas{% endblock %}

{% block body %}


<div class="filtros">
    <div class="buscar2">
        <h2 style="margin-top: 50px;">Buscador</h2>
        <form action=" {{ path('ofertas_index') }} " method='POST' id="buscador2">
            <label for="busqueda2"></label>
            <input type="text" name="busqueda" placeholder="¿Que quieres buscar?" /><br />
            <input style="width:60%" class="button primary" type="submit" value="Buscar">
        </form>
    </div><br>
    <button class="button primary" style="width:60%" type="button" onclick="mostrar()">Mostrar mas filtros</button><br><br>
    <div id="otros" style="display: none;">
        <div class="categoria">
            <form method="GET" action="{{ path('ofertas_index') }}">
                <h2>Categorias</h2>
                <select name="categorias" onchange="this.form.submit()">
                    <option value="">Seleccione categoría...</option>
                    {% for categoria in categorias %}
                    <option value={{ categoria.id }}>{{categoria.nombre}}</option>
                    {% endfor %}
                </select>
            </form>
        </div>
        <div class="isla">
            <form method="GET" action="{{ path('ofertas_index') }}">
                <h2>Localización</h2>
                <select name="localizacion" onchange="this.form.submit()">
                    <option value="">Seleccione isla...</option>
                    {% for isla in islas %}
                    <option value={{ isla.id }}>{{isla.nombre}}</option>
                    {% endfor %}
                </select><br>
            </form>
        </div>
        <div class="fecha">
            <form method="GET" action="{{ path('ofertas_index') }}">
                <h2>Fecha</h2>
                <label for="fecha1"></label>
                <input type="date" id="fecha1" name="fecha1">

                <label for="fecha2"></label>
                <input type="date" id="fecha2" name="fecha2"><br>

                <input style="width:60%" class="button primary" type="submit">
            </form>
        </div>
        <div class="actividad">
            <form method="GET" action="{{ path('ofertas_index') }}">
                <h2>Activo/Inactivo</h2>

                <select name="actividad" onchange="this.form.submit()">
                    <option value="">Seleccione actividad...</option>
                    <option value='true'>Activo</option>
                    <option value='false'>Inactivo</option>
                </select><br>
            </form>
        </div>
    </div>
</div>



<div class="listaofertas" style="margin-top:5%;">
    {% for oferta in ofertas %}
    {% if oferta.borrador == false %}
    <div class="elementosofertas">

        <h2 style="text-align:center">{{ oferta.puesto }}</h2>
        <h4 style="text-align:center">{{ oferta.tipo }}</h4>
        <p style="margin-left:5%;">{{ oferta.descripcion }}</p>


        <a style="width:80%;float: right;margin-right:10%" class="button primary"
            href="{{ path('ofertas_show', {'id': oferta.id}) }}">Mas
            detalles</a><br><br>


    </div><br>
    {% endif %}
    {% endfor %}

</div>

{% endblock %}

templates/ofertas/preguntas.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ofertas{% endblock %}

{% block body %}

<div class="editar">
    <h1 style="font-size: 2.5em;">Preguntas de interes</h1>
<div>
    <form action="{{ path('ofertas_registro')}}" method="POST">
    {% for pregunta in preguntas %}
    
        <label for="respuesta[]">{{pregunta.pregunta}}</label>
        <input type="text" name="respuesta[]" {% if pregunta.requerido == true %} required {% endif %}><br><br>
        <input type="hidden" name="preguntaid[]" value="{{ pregunta.id }}">
    {% endfor %}
    <input type="hidden" name="idempresa" value="{{ idempresa }}">
    <input type="hidden" name="idoferta" value="{{ idoferta }}">
    <input class="button primary" style="width:60%" type="submit" value="Enviar">
</form>
</div></div>
    {% endblock %}

templates/ofertas/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ofertas{% endblock %}

{% block body %}



<div class="datosOferta">
    <div id="elementos">
        <h1 style="font-size: 3em;">{{ oferta.puesto }}</h1>
            <h2 style="text-align: center">{% if oferta.activo == true %}Oferta activa {% else %} Oferta inactiva {%
                endif %}
            </h2>
            {% if registrado == true %}<h3 style="text-align: center">Numero de usuarios inscritos: {{numeroUsuarios}}
            </h3>{% endif %}
            <table class="table">
                <tbody>
                    <tr>
                        <th>Puesto</th>
                        <td>{{ oferta.puesto }}</td>
                    </tr>
                    <tr>
                        <th>Descripcion</th>
                        <td>{{ oferta.descripcion }}</td>
                    </tr>

                    <tr>
                        <th>Fecha</th>
                        <td>{{ oferta.fecha ? oferta.fecha|date('Y-m-d') : '' }}</td>
                    </tr>
                    <tr>
                        <th>Tipo de conrato</th>
                        <td>{{ oferta.tipo }}</td>
                    </tr>
                    <tr>
                        <th>Nombre empresa</th>
                        <td>{{ oferta.idempresa.nombre }}</td>
                    </tr>
                    <tr>
                        <th>Categoria</th>
                        <td>{{ oferta.categoria.nombre }}</td>
                    </tr>

                    <tr>
                        <th>Localizacion</th>
                        <td>
                            {% for isla in oferta.islas %}
                            {{ isla.nombre }}
                            {% endfor %}
                        </td>


                    </tr>



                </tbody>
            </table>

            {% if app.session.get('usuario') != "" and oferta.activo == true and registrado == false %}
            <form action="{{ path('ofertas_preguntas') }}" method="post">
                <input type="hidden" name="idempresa" value="{{ oferta.idempresa.id }}">
                <input type="hidden" name="idoferta" value="{{ oferta.id }}">

                <input style="width:50%;" class="button primary" type="submit" value="Inscribirme">
            </form>
            {% endif %}

            <a style="width:50%;" class="button primary" href="{{ path('ofertas_index') }}">Volver a la lista</a>
    </div>
</div>
{% endblock %}

templates/ofertas/usuariosInscritos.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ofertas{% endblock %}

{% block body %}

<div class="listaofertas">
    <h1 style="font-size: 3em; text-align: center;">Usuarios inscritos</h1>
    {% for ofertas in ofertas %}
    <div class="elementosofertas">
        {% if ofertas.descartado != true %}
        <h2 style="text-align: center;">{{ ofertas.usuarios.nombre }} {{ ofertas.usuarios.apellidos }}</h2>
        <a style="margin-right: 3%; width:95%" class="button primary" class="button primary"
            href="{{ path('usuarios_show', {'id': ofertas.usuarios.id})}}">Detalles usuario</a><br><br>

        <a style="margin-right: 3%; width:95%" class="button primary" class="button primary"
            href="{{ path('usuarios_crearCorreo', {'idUsuario': ofertas.usuarios.id, 'idOferta': ofertas.ofertas.id}) }}">Enviar
            correo</a><br><br>

        <a style="margin-right: 3%; width:95%" class="button primary" class="button primary"
            href="{{ path('empresas_respuestas', {'idUsuario': ofertas.usuarios.id, 'idOferta': ofertas.ofertas.id}) }}">Ver
            respuestas</a><br><br>

        <a style="margin-right: 3%; width:95%" class="button primary" class="button primary"
            href="{{ path('empresas_descartar', {'idUsuario': ofertas.usuarios.id, 'idOferta': ofertas.ofertas.id}) }}">Descartar
            Usuario</a><br><br>

        {% endif %}
    </div><br>
    {% else %}
    <h1 style="font-size: 1.5em;text-align: center;">No existe ningun usuario inscrito</h1>
    {% endfor %}
</div><br><br><br>
<a style="width:60%; margin-right:20%;margin-top:-4em; float:right" class="button primary" href="{{ path('empresas_perfil') }}">Volver al perfil</a></td>
</div>
{% endblock %}