src/Entity/Usuarios.php
<?php

namespace App\Entity;

use App\Repository\UsuariosRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=UsuariosRepository::class)
 */
class Usuarios
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nombre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $apellidos;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pass;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $dni;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $correo;

    /**
     * @ORM\Column(type="date")
     */
    private $fecha_nacimiento;

    /**
     * @ORM\Column(type="integer")
     */
    private $telefono;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $direccion;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $codigo_postal;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $pais;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $provincia;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $localidad;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cv;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $descripcion;

    /**
     * @ORM\OneToMany(targetEntity=UsuariosEmpresasOfertas::class, mappedBy="usuarios", orphanRemoval=true)
     */
    private $id_usuario;

    /**
     * @ORM\OneToMany(targetEntity=Respuestas::class, mappedBy="usuario")
     */
    private $respuestas;

    public function __construct()
    {
        $this->id_usuario = new ArrayCollection();
        $this->respuestas = new ArrayCollection();
    }

    
   
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getApellidos(): ?string
    {
        return $this->apellidos;
    }

    public function setApellidos(string $apellidos): self
    {
        $this->apellidos = $apellidos;

        return $this;
    }

    public function getPass(): ?string
    {
        return $this->pass;
    }

    public function setPass(string $pass): self
    {
        $this->pass = $pass;

        return $this;
    }

    public function getDni(): ?string
    {
        return $this->dni;
    }

    public function setDni(string $dni): self
    {
        $this->dni = $dni;

        return $this;
    }

    public function getCorreo(): ?string
    {
        return $this->correo;
    }

    public function setCorreo(string $correo): self
    {
        $this->correo = $correo;

        return $this;
    }

    public function getFechaNacimiento(): ?\DateTimeInterface
    {
        return $this->fecha_nacimiento;
    }

    public function setFechaNacimiento(\DateTimeInterface $fecha_nacimiento): self
    {
        $this->fecha_nacimiento = $fecha_nacimiento;

        return $this;
    }

    public function getTelefono(): ?int
    {
        return $this->telefono;
    }

    public function setTelefono(int $telefono): self
    {
        $this->telefono = $telefono;

        return $this;
    }

    public function getDireccion(): ?string
    {
        return $this->direccion;
    }

    public function setDireccion(?string $direccion): self
    {
        $this->direccion = $direccion;

        return $this;
    }

    public function getCodigoPostal(): ?int
    {
        return $this->codigo_postal;
    }

    public function setCodigoPostal(?int $codigo_postal): self
    {
        $this->codigo_postal = $codigo_postal;

        return $this;
    }

    public function getPais(): ?string
    {
        return $this->pais;
    }

    public function setPais(?string $pais): self
    {
        $this->pais = $pais;

        return $this;
    }

    public function getProvincia(): ?string
    {
        return $this->provincia;
    }

    public function setProvincia(?string $provincia): self
    {
        $this->provincia = $provincia;

        return $this;
    }

    public function getLocalidad(): ?string
    {
        return $this->localidad;
    }

    public function setLocalidad(?string $localidad): self
    {
        $this->localidad = $localidad;

        return $this;
    }

    public function getCv(): ?string
    {
        return $this->cv;
    }

    public function setCv(?string $cv): self
    {
        $this->cv = $cv;

        return $this;
    }

    public function getDescripcion(): ?string
    {
        return $this->descripcion;
    }

    public function setDescripcion(?string $descripcion): self
    {
        $this->descripcion = $descripcion;

        return $this;
    }

    public function getUsuarios(): ?self
    {
        return $this->usuarios;
    }

    public function setUsuarios(?self $usuarios): self
    {
        $this->usuarios = $usuarios;

        return $this;
    }

    /**
     * @return Collection|UsuariosEmpresasOfertas[]
     */
    public function getIdUsuario(): Collection
    {
        return $this->id_usuario;
    }

    public function addIdUsuario(UsuariosEmpresasOfertas $idUsuario): self
    {
        if (!$this->id_usuario->contains($idUsuario)) {
            $this->id_usuario[] = $idUsuario;
            $idUsuario->setUsuarios($this);
        }

        return $this;
    }

    public function removeIdUsuario(UsuariosEmpresasOfertas $idUsuario): self
    {
        if ($this->id_usuario->removeElement($idUsuario)) {
            // set the owning side to null (unless already changed)
            if ($idUsuario->getUsuarios() === $this) {
                $idUsuario->setUsuarios(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Respuestas[]
     */
    public function getRespuestas(): Collection
    {
        return $this->respuestas;
    }

    public function addRespuesta(Respuestas $respuesta): self
    {
        if (!$this->respuestas->contains($respuesta)) {
            $this->respuestas[] = $respuesta;
            $respuesta->setUsuario($this);
        }

        return $this;
    }

    public function removeRespuesta(Respuestas $respuesta): self
    {
        if ($this->respuestas->removeElement($respuesta)) {
            // set the owning side to null (unless already changed)
            if ($respuesta->getUsuario() === $this) {
                $respuesta->setUsuario(null);
            }
        }

        return $this;
    }

}

src/Form/UsuariosType.php
<?php

namespace App\Form;

use App\Entity\Usuarios;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UsuariosType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nombre')
            ->add('apellidos')
            ->add('pass', PasswordType::class)
            ->add('dni')
            ->add('correo')
            ->add('fecha_nacimiento')
            ->add('telefono')
            ->add('direccion')
            ->add('codigo_postal')
            ->add('pais')
            ->add('provincia')
            ->add('localidad')
            ->add('cv')
            ->add('descripcion')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Usuarios::class,
        ]);
    }
}

src/Controller/UsuariosController.php
<?php

namespace App\Controller;

use App\Entity\Usuarios;
use App\Form\UsuariosType;
use App\Repository\EmpresasRepository;
use App\Repository\OfertasRepository;
use App\Repository\UsuariosRepository;
use App\Service\Correos;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\String\Slugger\SluggerInterface;

/**
 * @Route("/usuarios")
 */
class UsuariosController extends AbstractController
{
    /**
     * Funcion que nos permitira logear a un usuario
     * @Route("/login", name="usuarios_login", methods={"GET", "POST"})
     */
    public function usuariosLogin(UsuariosRepository $usuariosRepository, EntityManagerInterface $em, Request $request, SessionInterface $session): Response
    {
        $correo = $request->request->get('correo');
        $pass = $request->request->get('pass');
        $usuario = $usuariosRepository->findOneBy(['correo' => $correo]);

        if ($request->request->get('correo') != "") {
            // Si el correo existe, comprobamos las contraseñas y creamos la sesion del usuario
            if (!empty($usuario)) {
                if (password_verify($pass, $usuario->getPass())) {
                    $session->set('usuario', ['correo' => $usuario->getCorreo(), 'id' => $usuario->getId()]);
                    return $this->redirectToRoute('usuarios_perfil');
                } else {
                    // Si es incorrecta la contraseña, se devuelve a la pagina con un error
                    return $this->render('usuarios/login.html.twig', [
                        'usuarios' => $usuariosRepository->findAll(),
                        'error' => 'Error: contraseña incorrecta',
                    ]);
                }
            } else {
                // Si es incorrecto el correo, se devuelve a la pagina con un error
                return $this->render('usuarios/login.html.twig', [
                    'usuarios' => $usuariosRepository->findAll(),
                    'error' => 'Error: el correo indicado no existe',
                ]);
            }
        }

        return $this->render('usuarios/login.html.twig', [
            'usuarios' => $usuariosRepository->findAll(),
        ]);
    }

    /**
     * Genera el perfil de un usuario
     * @Route("/perfil", name="usuarios_perfil", methods={"GET"})
     */
    public function usuariosPerfil(UsuariosRepository $usuariosRepository, SessionInterface $session): Response
    {
        return $this->render('usuarios/perfil.html.twig', [
            'usuario' => $usuariosRepository->findOneBy(['correo' => $session->get('usuario')['correo']]),
        ]);
    }

    /**
     * Cierra la sesion de un usuario
     * @Route("/cerrarSesion", name="usuarios_cerrar_sesion", methods={"GET"})
     */
    public function usuariosCerrarSesion(UsuariosRepository $usuariosRepository, SessionInterface $session): Response
    {
        $session->remove('usuario'); // Elimina la sesion del usuario
        return $this->render('usuarios/login.html.twig', [
            'usuarios' => $usuariosRepository->findAll(),
        ]);
    }

    /**
     * Funcion que permite la creacion de un usuario.
     * @Route("/crear", name="usuarios_crear", methods={"GET","POST"})
     */
    public function crearUsuario(Request $request, EntityManagerInterface $em): Response
    {
        $usuario = new Usuarios();
        $nombre = $request->request->get('nombre');
        $identificacion = $request->request->get('identificacion');
        $apellidos = $request->request->get('apellidos');
        $pass = $request->request->get('pass');
        $pass2 = $request->request->get('pass2');
        $correo = $request->request->get('correo');
        $correo2 = $request->request->get('correo2');
        $fecha_nacimiento = $request->request->get('fecha_nacimiento');
        $telefono = $request->request->get('telefono');
        // Comprobacion de que tanto los correos como las contraseñas son iguales
        if ($pass == $pass2 && $correo == $correo2) {
            if (!empty($nombre)) {

                $em = $this->getDoctrine()->getManager();
                $usuario->setNombre($nombre);
                $usuario->setDni($identificacion);
                $usuario->setApellidos($apellidos);
                $usuario->setPass(password_hash($pass, PASSWORD_DEFAULT));
                $usuario->setCorreo($correo);
                // Colocamos la fecha de nacimiento de la siguiente manera
                $usuario->setFechaNacimiento(\DateTime::createFromFormat('Y-m-d', $fecha_nacimiento));
                $usuario->setTelefono($telefono);
                $em->persist($usuario);
                $em->flush();
                return $this->redirectToRoute('usuarios_crear');
            }
        }
        return $this->render('usuarios/crear.html.twig', [
            'usuario' => $usuario
        ]);
    }

    /**
     * Esta funcion nos permite editar la informacion de un usuario.
     * @Route("/editar", name="usuarios_editar", methods={"GET","POST"})
     */
    public function editar(Request $request, UsuariosRepository $usuariosRepository, SessionInterface $session, SluggerInterface $slugger): Response
    {
        $usuario = $usuariosRepository->findOneBy(['id' => $session->get('usuario')['id']]);
        if ($request->get('nombre')) {
            $nombre = $request->get('nombre');
            $apellidos = $request->get('apellidos');
            $telefono = $request->get('telefono');
            if (!empty($nombre) && !empty($apellidos) && !empty($telefono)) {
                $em = $this->getDoctrine()->getManager();
                $usuario->setNombre($nombre);
                $usuario->setApellidos($apellidos);
                $usuario->setTelefono($telefono);
                // Si en el request no esta vacio, hacemos set al valor, en caso contrario no hacemos nada
                !empty($request->get('direccion')) ? $usuario->setDireccion($request->get('direccion')) : null;
                !empty($request->get('codigo_postal')) ? $usuario->setCodigoPostal($request->get('codigo_postal')) : null;
                !empty($request->get('pais')) ? $usuario->setPais($request->get('pais')) : null;
                !empty($request->get('provincia')) ? $usuario->setProvincia($request->get('provincia')) : null;
                !empty($request->get('localidad')) ? $usuario->setLocalidad($request->get('localidad')) : null;
                !empty($request->get('descripcion')) ? $usuario->setDescripcion($request->get('descripcion')) : null;

                //Subir CV
                if (!empty($request->files->get('cv'))) {
                    // Recogemos el fichero y tambien le creamos un nuevo nombre de forma segura
                    $archivo = $request->files->get('cv');
                    $originalFilename = pathinfo($archivo->getClientOriginalName(), PATHINFO_FILENAME);
                    $safeFilename = $slugger->slug($originalFilename);
                    $newFilename = $safeFilename . '-' . uniqid() . '.' . $archivo->guessExtension();

                    // Movemos el fichero a nuestra carpeta publica
                    $archivo->move('uploads/cv', $newFilename);

                    $usuario->setCv($newFilename);
                }

                $em->persist($usuario);
                $em->flush();
                return $this->redirectToRoute('usuarios_perfil');
            }
        }


        return $this->render('usuarios/editar.html.twig', [
            'usuario' => $usuario,
        ]);
    }

    /**
     * Esta funcion nos permite ver la informacion de un usuario.
     * @Route("/{id}", name="usuarios_show", methods={"GET"})
     */
    public function show(Usuarios $usuario): Response
    {
        return $this->render('usuarios/show.html.twig', [
            'usuario' => $usuario,
        ]);
    }

    /**
     * Esta funcion permitira mandar a las empresas un correo al usuario.
     * @Route("/crearCorreo/{idOferta}/{idUsuario}", name="usuarios_crearCorreo", methods={"GET", "POST"})
     */
    public function crearCorreo($idUsuario, $idOferta, Request $request, MailerInterface $mailer, SessionInterface $session, EmpresasRepository $empresasRepository, OfertasRepository $ofertasRepository, UsuariosRepository $usuariosRepository, Correos $correos): Response
    {
        if ($request->get('asunto') != "") {
            
            $oferta = $ofertasRepository->findOneBy(['id' => $idOferta]);
            $empresa = $empresasRepository->findOneBy(['id' => $session->get('empresa')['id']]);
            // Comprobamos que la oferta es de la empresa que se encuentra en sesion
            if ($empresa != $oferta->getIdEmpresa()) {
                return $this->redirectToRoute('index');
            }

            $correoUsuario = $usuariosRepository->findOneBy(['id' => $idUsuario])->getCorreo();
            // Enviar correo
            $correos->crearCorreo($correoUsuario, $empresa, $oferta, $request->get('asunto'), $request->get('mensaje'), true, true);

        return $this->redirectToRoute('empresas_perfil');
        }

        return $this->render('usuarios/correo.html.twig', [
            'id' => $idUsuario,
            'oferta' => $idOferta
        ]);
    }

}
        

templates/usuarios/_formulario.html.twig
<div>
    <form action="{{ accion }}" method="post" class="formulario" onsubmit="manejador(event)">
        <label for="identificacion">NIF/CIF/Pasaporte: </label>
        <input type="text" name="identificacion" id="identificacion" required><br>

        <label for="nombre">Nombre: </label>
        <input type="text" name="nombre" id="nombre" required><br>
        
        <label for="apellidos">Apellidos: </label>
        <input type="text" name="apellidos" id="apellidos" required><br>

        <label for="correo">Correo electronico: </label>
        <input type="email" name="correo" id="correo" required>

        <label for="correo2">Repita el correo: </label>
        <input type="email" name="correo2" id="correo2" required><br>

        <label for="pass">Contraseña: </label>
        <input type="password" name="pass" id="pass" required>

        <label for="pass2">Repita la contraseña: </label>
        <input type="password" name="pass2" id="pass2" required><br>

        <label for="fecha_nacimiento">Fecha de nacimiento: </label>
        <input type="date" name="fecha_nacimiento" id="fecha_nacimiento" required><br>

        <label for="telefono">Telefono: </label>
        <input type="tel" name="telefono" id="telefono" required><br>
        
        <input style="width:60%;" class="button primary" type="submit" value="Registrarse">
    </form>
</div>

templates/usuarios/correo.html.twig
{% extends 'base.html.twig' %}

{% block title %}Enviar correo{% endblock %}

{% block body %}

<div class="editar">
    <h1 style="font-size: 2.5em;">Contacto con el usuario</h1>
    <div id="envioCorreo">
        <form action="{{ path('usuarios_crearCorreo', {'idUsuario': id, 'idOferta': oferta})}}">
            <label style="font-size: 1.5em;" for="asunto">Asunto:</label>
            <input type="text" name="asunto" id="asunto" required><br><br>

            <label style="font-size: 1.5em;" for="mensaje">Mensaje:</label>
            <textarea name="mensaje" rows="10" cols="50"
                placeholder="Escriba el contenido del correo"></textarea><br><br>

            <input style="width:60%;" class="button primary" type="submit" value="Enviar">
        </form>
    </div>
    <a style="width:60%" class="button primary" href="{{ path('ofertas_usuarios_inscritos', {'id': oferta}) }}">Atras</a>
</div>
{% endblock %}

templates/usuarios/crear.html.twig
{% extends "base.html.twig" %}

{% block title %}
    Usuario
{% endblock title %}

{% block javascripts %}

<script src="{{asset('js/validar.js')}}"></script>
<script src="{{asset('js/loading.js')}}"></script>
<script src="{{asset('js/jquery.min.js')}}"></script>
<script src="{{asset('js/jquery.scrolly.min.js')}}"></script>
<script src="{{asset('js/jquery.dropotron.min.js')}}"></script>
<script src="{{asset('js/jquery.scrollex.min.js')}}"></script>
<script src="{{asset('js/browser.min.js')}}"></script>
<script src="{{asset('js/breakpoints.min.js')}}"></script>
<script src="{{asset('js/util.js')}}"></script>
<script src="{{asset('js/main.js')}}"></script>

{% endblock javascripts %}

{% block body %}
<div class="registro">
    <h1 style="font-size: 2em;">Crear Usuario</h1>
    {% include "usuarios/_formulario.html.twig" with {'accion': path('usuarios_crear') }%}
</div>
{% endblock body %}

templates/usuarios/editar.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editar Perfil{% endblock %}

{% block body %}
<div class="editar">
    <div>
        <h1 style="font-size: 2em;">Editar perfil</h1>
        <form action="{{ path('usuarios_editar') }}" class="formulario" enctype="multipart/form-data" method="post">
            <label for="nombre">Nombre: </label>
            <input type="text" name="nombre" id="nombre" value="{{ usuario.nombre }}"><br>

            <label for="apellidos">Apellidos: </label>
            <input type="text" name="apellidos" id="apellidos" value="{{ usuario.apellidos }}" required><br>

            <label for="telefono">Telefono: </label>
            <input type="tel" name="telefono" id="telefono" value="{{ usuario.telefono }}" required><br>

            <label for="cv">CV: </label>
            <input type="file" name="cv" id="cv"><br>

            <label for="direccion">Dirección: </label>
            <input type="text" name="direccion" id="direccion" value="{{ usuario.direccion }}"><br>

            <label for="codigo_postal">Codigo postal: </label>
            <input type="number" name="codigo_postal" id="codigo_postal" value="{{ usuario.codigopostal }}"><br>

            <label for="pais">Pais: </label>
            <input type="text" name="pais" id="pais" value="{{ usuario.pais }}"><br>

            <label for="provincia">Provincia: </label>
            <input type="text" name="provincia" id="provincia" value="{{ usuario.provincia }}"><br>

            <label for="localidad">Localidad: </label>
            <input type="text" name="localidad" id="localidad" value="{{ usuario.localidad }}"><br>

            <label for="descripcion">Descripcion: </label>
            <textarea id="descripcion" name="descripcion">{{ usuario.descripcion }}</textarea><br>

            <input style="width:60%;" class="button primary" type="submit" value="Registrarse">
        </form>

        <a  style="width:60%;" class="button primary" href="{{ path('usuarios_perfil') }}">Volver al perfil</a>
    </div>
</div>
{% endblock %}

templates/usuarios/login.html.twig
{% extends "base.html.twig" %}

{% block title %}Login Usuarios{% endblock %}


{% block body %}
<div class="login">
    <h1 style="font-size: 2em;">Inicio sesión usuarios</h1>
    <form action='{{ path('usuarios_login') }}' method="post">
        <label for="correo">Correo electrónico: </label>
        <input type="email" name="correo" id="correo" required></br>

        <label for="pass">Contraseña: </label>
        <input type="password" name="pass" id="pass" required></br>

        <input style="width:60%;" class="button primary" type="submit" value="Iniciar Sesion">
    </form>
{% if error is defined %} 

<p>{{ error }}</p>

{% endif %}
</div>
{% endblock %}

templates/usuarios/perfil.html.twig
{% extends 'base.html.twig' %}

{% block title %}Perfil Usuarios{% endblock %}

{% block body %}
{# {% set filter = app.session.get('empresa') %} #}

<div class="perfil">
    <h1 style="font-size: 2em;">¡Bienvenido {{ usuario.nombre }}!</h1>
    <div id="enlaces" style="margin-top: 20px;">
        <a style="width:60%;" class="button primary" href="{{ path('usuarios_show', {'id': usuario.id}) }}">Detalles</a><br><br>
        <a style="width:60%;" class="button primary" href="{{ path('usuarios_editar') }}">Editar detalles</a><br><br>
        <a style="width:60%;" class="button primary" href="{{ path('ofertas_listausuario') }}">Mostrar ofertas</a><br><br>
        
        
    </div>
</div>
{% endblock %}

templates/usuarios/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Usuarios{% endblock %}

{% block body %}
<div class="datosEmpresa">
    <div id="elementos">
        <h1 style="font-size: 3em;">{{usuario.nombre}} {{ usuario.apellidos }}</h1>
        <table class="table">
        <tbody>

            <tr>
                <th>DNI</th>
                <td>{{ usuario.dni }}</td>
            </tr>
            <tr>
                <th>Correo</th>
                <td>{{ usuario.correo }}</td>
            </tr>
            <tr>
                <th>Fecha_nacimiento</th>
                <td>{{ usuario.fechaNacimiento ? usuario.fechaNacimiento|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Telefono</th>
                <td>{{ usuario.telefono }}</td>
            </tr>
            <tr>
                <th>Direccion</th>
                <td>{{ usuario.direccion }}</td>
            </tr>
            <tr>
                <th>Codigo_postal</th>
                <td>{{ usuario.codigoPostal }}</td>
            </tr>
            <tr>
                <th>Pais</th>
                <td>{{ usuario.pais }}</td>
            </tr>
            <tr>
                <th>Provincia</th>
                <td>{{ usuario.provincia }}</td>
            </tr>
            <tr>
                <th>Localidad</th>
                <td>{{ usuario.localidad }}</td>
            </tr>
            <tr>
                <th>Cv</th>
                {% if usuario.cv != "" %}<td><a href="{{ asset('uploads/cv/' ~ usuario.cv) }}" >Ver CV</a>{% endif %}
                </td>
            </tr>
            <tr>
                <th>Descripcion</th>
                <td>{{ usuario.descripcion }}</td>
            </tr>
        </tbody>
    </table>
    {% if app.session.get('usuario') != "" %}
    <a style="width:60%;"class="button primary" href="{{ path('usuarios_perfil') }}">Volver al perfil</a>
    {% else %}
    <a class="button primary" style="width:60%;margin-left:80%; margin-top:40px" href="{{ app.request.server.get('HTTP_REFERER')}}">Atras</a>

    {% endif %}
</div>

</div>
{% endblock %}